"use client";
import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "el" | "en" | "es" | "ar" | "pt" | "de";
export type Theme = "dark" | "light";

export const LANG_LABELS: Record<Language, { label: string; flag: string; dir?: string }> = {
  el: { label: "Ελληνικά", flag: "🇬🇷" },
  en: { label: "English", flag: "🇬🇧" },
  es: { label: "Español", flag: "🇪🇸" },
  ar: { label: "العربية", flag: "🇸🇦", dir: "rtl" },
  pt: { label: "Português", flag: "🇵🇹" },
  de: { label: "Deutsch", flag: "🇩🇪" },
};

export type TranslationKey =
  | "nav_tickets" | "nav_program" | "nav_competition" | "nav_photos"
  | "nav_sponsors" | "nav_contact" | "nav_location"
  | "nav_general_admission" | "nav_competition_cost"
  | "nav_mainstage" | "nav_competition_topics" | "nav_student"
  | "nav_fees" | "nav_rules"
  | "home_hero_subtitle" | "home_hero_cta" | "home_educators_title"
  | "home_sponsors_title" | "home_videos_title"
  | "tickets_title" | "tickets_general" | "tickets_competition"
  | "location_title" | "location_address" | "location_map_btn"
  | "contact_title" | "photos_title" | "sponsors_title"
  | "program_title" | "program_mainstage" | "competition_title"
  | "student_title" | "rules_title" | "fees_title"
  | "coming_soon" | "learn_more" | "register_now" | "view_map"
  | "location_desc1" | "location_desc2" | "location_cartel" | "location_date"
  | "contact_person_label" | "contact_follow"
  | "program_stage_desc" | "program_stage_btn"
  | "comp_description" | "comp_requirements" | "comp_criteria" | "comp_time"
  | "fees_desc" | "fees_link"
  | "mainstage_coming" | "mainstage_note"
  | "general_admission_title" | "comp_fee_title"
  | "home_about" | "home_tagline" | "home_date"
  | "comp_topics_title" | "comp_overview_intro"
  | "presale_title" | "crew_presale_title" | "crew_general_title" | "special_prices"
  | "professionals" | "students_label" | "prof_desc" | "student_desc"
  | "companions_note" | "info_phones" | "form_title"
  | "form_name" | "form_surname" | "form_phone" | "form_postal" | "form_address" | "form_city"
  | "form_category" | "form_professional" | "form_student_opt"
  | "prof_comp_title" | "one_topic_label" | "multi_topics_title"
  | "student_comp_fees" | "free_admission" | "comp_fee_notes"
  | "best_barber_note" | "comp_single_note" | "per_person" | "bonus_note"
  | "tickets_prof_students" | "tickets_cost_note" | "tickets_more"
  | "photos_thanks" | "photos_download" | "photos_see_you"
  | "student_notes_title" | "student_registration" | "student_terms"
  | "student_intro" | "student_eligibility" | "student_awards" | "student_mandatory"
  | "student_price_note" | "student_fast_time" | "student_fast_desc"
  | "student_freestyle_time" | "student_freestyle_desc" | "student_contact_note"
  | "footer_phones" | "footer_links" | "footer_date_venue"
  | "hero_city" | "hero_factory" | "hero_address_short" | "hero_tickets_btn" | "hero_competition_btn"
  | "countdown_days" | "countdown_hours" | "countdown_minutes" | "countdown_seconds"
  | "comp_notes_title" | "comp_notes_more" | "comp_notes_link"
  | "comp_cat_oldschool_desc" | "comp_cat_modern_desc" | "comp_cat_fastest_desc" | "comp_cat_freestyle_desc"
  | "comp_cat_time_unit"
  | "nav_student_comp" | "nav_comp_cost" | "nav_comp_rules";

type Translations = Record<TranslationKey, string>;

const T: Record<Language, Translations> = {
  el: {
    nav_tickets: "ΕΙΣΙΤΗΡΙΑ",
    nav_program: "ΠΡΟΓΡΑΜΜΑ",
    nav_competition: "ΔΙΑΓΩΝΙΣΜΟΣ",
    nav_photos: "ΦΩΤΟΓΡΑΦΙΕΣ",
    nav_sponsors: "ΧΟΡΗΓΟΙ",
    nav_contact: "ΕΠΙΚΟΙΝΩΝΙΑ",
    nav_location: "ΤΟΠΟΘΕΣΙΑ",
    nav_general_admission: "Γενική Είσοδος",
    nav_competition_cost: "Διαγωνισμός",
    nav_mainstage: "Κεντρική Σκηνή",
    nav_competition_topics: "Διαγωνιστικά Θέματα",
    nav_student: "Μαθητικός Διαγωνισμός",
    nav_fees: "Κόστος Συμμετοχής",
    nav_rules: "Όροι Συμμετοχής",
    home_hero_subtitle: "EDUCATION · SHOWS · COMPETITIONS",
    home_hero_cta: "ΑΓΟΡΑ ΕΙΣΙΤΗΡΙΩΝ",
    home_educators_title: "GUEST EDUCATORS 2026",
    home_sponsors_title: "ΧΟΡΗΓΟΙ",
    home_videos_title: "AFTER MOVIES",
    tickets_title: "ΕΙΣΙΤΗΡΙΑ",
    tickets_general: "Γενική Είσοδος",
    tickets_competition: "Κόστος Διαγωνισμού",
    location_title: "ΤΟΠΟΘΕΣΙΑ",
    location_address: "Παρ. Λεωφόρος Κηφισσού 42, Αιγάλεω",
    location_map_btn: "Δείτε το χάρτη",
    contact_title: "ΕΠΙΚΟΙΝΩΝΙΑ",
    photos_title: "ΦΩΤΟΓΡΑΦΙΕΣ",
    sponsors_title: "ΧΟΡΗΓΟΙ",
    program_title: "ΠΡΟΓΡΑΜΜΑ",
    program_mainstage: "Κεντρική Σκηνή",
    competition_title: "ΔΙΑΓΩΝΙΣΜΟΣ",
    student_title: "ΜΑΘΗΤΙΚΟΣ ΔΙΑΓΩΝΙΣΜΟΣ",
    rules_title: "ΟΡΟΙ ΣΥΜΜΕΤΟΧΗΣ",
    fees_title: "ΚΟΣΤΟΣ ΣΥΜΜΕΤΟΧΗΣ",
    coming_soon: "Σύντομα...",
    learn_more: "Περισσότερα →",
    register_now: "ΕΓΓΡΑΦΗ",
    view_map: "ΔΕΙΤΕ ΤΟ ΧΑΡΤΗ",
    location_desc1: "Το 8ο Greek Barber Festival θα πραγματοποιηθεί στους εργοστασιακούς χώρους της ιστορικής κλωστοϋφαντουργίας \"Κλωσταί Πεταλούδα\" στην παρ. Λεωφόρου Κηφισσού 42 στο Αιγάλεω.",
    location_desc2: "Ο χώρος είναι εύκολα προσβάσιμος μέσω της Γραμμής του Μετρό, μόλις 11-12 λεπτά περπάτημα από τους σταθμούς Αιγάλεω και Ελαιώνας.",
    location_cartel: "( δίπλα στον Τεχνοχώρο \"CARTEL\" )",
    location_date: "26-27 Απριλίου 2026 — ΑΘΗΝΑ",
    contact_person_label: "Υπεύθυνη Επικοινωνίας",
    contact_follow: "Βρείτε μας & Ακολουθήστε μας",
    program_stage_desc: "Δείτε το πρόγραμμα της κεντρικής σκηνής",
    program_stage_btn: "ΠΡΟΓΡΑΜΜΑ ΣΚΗΝΗΣ",
    comp_description: "Περιγραφή",
    comp_requirements: "Προϋποθέσεις:",
    comp_criteria: "Κριτήρια:",
    comp_time: "Χρόνος:",
    fees_desc: "Για πλήρεις τιμές και δήλωση συμμετοχής:",
    fees_link: "Μεταβείτε στη σελίδα κόστους συμμετοχής",
    mainstage_coming: "Το πρόγραμμα θα ανακοινωθεί σύντομα",
    mainstage_note: "Το αναλυτικό πρόγραμμα της κεντρικής σκηνής θα δημοσιευτεί πριν την εκδήλωση.",
    general_admission_title: "ΓΕΝΙΚΗ ΕΙΣΟΔΟΣ",
    comp_fee_title: "ΚΟΣΤΟΣ ΣΥΜΜΕΤΟΧΗΣ",
    home_about: "Το 8ο Greek Barber Festival είναι το σημείο συνάντησης της barber κουλτούρας στην Ελλάδα. Για 2 μέρες οι εμβληματικοί εργοστασιακοί χώροι της ιστορικής κλωστοϋφαντουργίας «Κλωσταί Πεταλούδα» στην Αθήνα, μετατρέπονται σε κέντρο έμπνευσης, εκπαίδευσης και δημιουργίας. Ζωντανές παρουσιάσεις, εκπαιδευτικά σεμινάρια και διαγωνισμοί δημιουργούν μια μοναδική εμπειρία γνώσης, έμπνευσης και επαγγελματικής εξέλιξης.",
    home_tagline: "Εκπαίδευση - Εξέλιξη - Επιτυχία",
    home_date: "26-27 Απριλίου 2026",
    comp_topics_title: "ΔΙΑΓΩΝΙΣΤΙΚΑ ΘΕΜΑΤΑ",
    comp_overview_intro: "Ο μεγαλύτερος διαγωνισμός στην Ελλάδα όπου συμμετέχουν οι κορυφαίοι barbers με αναγνωρισιμότητα σε παγκόσμιο επίπεδο. Ο διαγωνισμός πληρεί ευρωπαϊκές προδιαγραφές και κριτές είναι ξένοι αναγνωρισμένοι εκπαιδευτές από όλη την Ευρώπη. Δηλώστε συμμετοχή και διεκδικήστε τον τίτλο «Best Barber of the Year 2026» καθώς και πλούσια δώρα. Τα θέματα είναι 4. Μπορείτε να δηλώσετε συμμετοχή σε ένα ή περισσότερα. Για τον τίτλο χρειάζονται τουλάχιστον 3 θέματα.",
    presale_title: "Προπώληση έως 28 Φεβρουαρίου 2026",
    crew_presale_title: "Festival Crew Bonus — Προπώληση",
    crew_general_title: "Festival Crew Bonus — Γενική Είσοδος",
    special_prices: "Επωφελήσου από τις ειδικές τιμές.",
    professionals: "Επαγγελματίες*",
    students_label: "Σπουδαστές σχολών*",
    prof_desc: "*Ιδιοκτήτες και Υπάλληλοι Καταστημάτων, Freelancers, Απόφοιτοι ιδιωτικής ή δημόσιας σχολής.",
    student_desc: "*(απαιτείται βεβαίωση σπουδών)",
    companions_note: "Σημείωση: Επιτρέπονται οι συνοδοί (Α' βαθμού συγγένειας) με γενική είσοδο €30.00",
    info_phones: "Για περισσότερες πληροφορίες στα τηλέφωνα:",
    form_title: "ΦΟΡΜΑ ΕΓΓΡΑΦΗΣ",
    form_name: "Όνομα",
    form_surname: "Επίθετο",
    form_phone: "Τηλέφωνο",
    form_postal: "ΤΚ",
    form_address: "Διεύθυνση",
    form_city: "Πόλη",
    form_category: "Επιλέξτε κατηγορία",
    form_professional: "Επαγγελματίας",
    form_student_opt: "Σπουδαστής",
    prof_comp_title: "ΕΠΑΓΓΕΛΜΑΤΙΚΟΣ ΔΙΑΓΩΝΙΣΜΟΣ",
    one_topic_label: "Για 1 διαγωνιστικό θέμα:",
    multi_topics_title: "Πολλαπλά θέματα",
    student_comp_fees: "ΜΑΘΗΤΙΚΟΣ ΔΙΑΓΩΝΙΣΜΟΣ",
    free_admission: "(ΔΩΡΕΑΝ γενική είσοδος)",
    comp_fee_notes: "*Τα ονόματα των μοντέλων υποχρεωτικό να δηλωθούν 15 μέρες πριν. *Μοντέλα για 1-2 θέματα: €50 είσοδος. *Μοντέλα χωρίς σχέση με τον χώρο αποχωρούν μετά τη λήξη κάθε θέματος.",
    best_barber_note: "Για τίτλο «Best Barber of the Year» → τουλάχιστον 3 θέματα.",
    comp_single_note: "*Οι παραπάνω τιμές ισχύουν για την επιλογή ενός διαγωνιστικού θέματος.",
    per_person: "/ άτομο",
    bonus_note: "Bonus 10 βαθμών από τον κάθε κριτή, σε έναν και μόνο διαγωνιζόμενο.",
    tickets_prof_students: "Επαγγελματίες & Σπουδαστές",
    tickets_cost_note: "Κόστος ανά θέμα / πολλαπλά θέματα",
    tickets_more: "ΠΕΡΙΣΣΟΤΕΡΑ",
    photos_thanks: "Σας ευχαριστούμε όλους όσους ήσασταν μαζί μας!",
    photos_download: "Μπορείτε να κατεβάσετε τις φωτογραφίες, να κάνετε «καρδούλα» και να τις μοιραστείτε στα μέσα κοινωνικής δικτύωσης.",
    photos_see_you: "Ραντεβού στο 8ο Greek Barber Festival 26-27 Απριλίου 2026, ΑΘΗΝΑ",
    student_notes_title: "Σημαντικές Σημειώσεις",
    student_registration: "ΔΗΛΩΣΗ ΣΥΜΜΕΤΟΧΗΣ",
    student_terms: "Αποδέχομαι τους κανονισμούς και δηλώνω συμμετοχή και στα 2 διαγωνιστικά θέματα",
    student_intro: "Στα πλαίσια του 8ου Greek Barber Festival θα διοργανωθεί μαθητικός διαγωνισμός.",
    student_eligibility: "Μπορούν να συμμετέχουν μαθητές σχολών κομμωτικής από δημόσιες, ιδιωτικές, ΕΠΑΛ και ΙΕΚ σχολές.",
    student_awards: "Τα βραβεία θα επιβραβεύουν τις ικανότητες και την επίδοση των διαγωνιζόμενων, κριμένων από τους αυστηρότερους κριτές. Τα διαγωνιστικά θέματα είναι 2:",
    student_mandatory: "Είναι υποχρεωτικό να δηλώσετε συμμετοχή και στα 2 διαγωνιστικά θέματα.",
    student_price_note: "(στην τιμή συμπεριλαμβάνεται και η είσοδος στο φεστιβάλ)",
    student_fast_time: "Χρόνος: 15 λεπτά",
    student_fast_desc: "Αυτό το θέμα αφορά τον πιο γρήγορο και τον πιο καλό τεχνίτη.",
    student_freestyle_time: "Χρόνος: 60 λεπτά",
    student_freestyle_desc: "Θα διαγωνιστείς σε ελεύθερο θέμα χρησιμοποιώντας την φαντασία σου.",
    student_contact_note: "Για περισσότερες πληροφορίες επικοινωνήστε στα τηλέφωνα",
    footer_phones: "Τηλέφωνα Επικοινωνίας",
    footer_links: "Σύνδεσμοι",
    footer_date_venue: "26-27 Απριλίου 2026 ΑΘΗΝΑ",
    hero_city: "ΑΘΗΝΑ",
    hero_factory: "ΕΡΓΟΣΤΑΣΙΟ «ΚΛΩΣΤΑΊ ΠΕΤΑΛΟΎΔΑ»",
    hero_address_short: "Παρ. Λεωφόρος Κηφισσού 42, Αιγάλεω (πλησίον Τεχνοχώρου «Cartel»)",
    hero_tickets_btn: "ΕΙΣΙΤΗΡΙΑ",
    hero_competition_btn: "ΔΙΑΓΩΝΙΣΜΟΣ",
    countdown_days: "ΗΜΕΡΕΣ",
    countdown_hours: "ΩΡΕΣ",
    countdown_minutes: "ΛΕΠΤΑ",
    countdown_seconds: "ΔΕΥΤ.",
    comp_notes_title: "Σημαντικές Σημειώσεις",
    comp_notes_more: "Για περισσότερες πληροφορίες σχετικά με τους όρους,",
    comp_notes_link: "δείτε τους Όρους Συμμετοχής",
    comp_cat_oldschool_desc: "Θα διαγωνιστείς σε old school κούρεμα της επιλογής σου.",
    comp_cat_modern_desc: "Θα διαγωνιστείς σε ένα modern haircut της επιλογής σου.",
    comp_cat_fastest_desc: "Αυτό το θέμα αφορά τον πιο γρήγορο και τον πιο καλό τεχνίτη.",
    comp_cat_freestyle_desc: "Θα διαγωνιστείς σε ελεύθερο θέμα χρησιμοποιώντας την φαντασία σου.",
    comp_cat_time_unit: "λεπτά",
    nav_student_comp: "Μαθητικός Διαγωνισμός",
    nav_comp_cost: "Κόστος Συμμετοχής",
    nav_comp_rules: "Όροι Συμμετοχής",
  },
  en: {
    nav_tickets: "TICKETS",
    nav_program: "PROGRAM",
    nav_competition: "COMPETITION",
    nav_photos: "PHOTOS",
    nav_sponsors: "SPONSORS",
    nav_contact: "CONTACT",
    nav_location: "LOCATION",
    nav_general_admission: "General Admission",
    nav_competition_cost: "Competition",
    nav_mainstage: "Main Stage",
    nav_competition_topics: "Competition Categories",
    nav_student: "Student Competition",
    nav_fees: "Entry Fees",
    nav_rules: "Rules & Terms",
    home_hero_subtitle: "EDUCATION · SHOWS · COMPETITIONS",
    home_hero_cta: "BUY TICKETS",
    home_educators_title: "GUEST EDUCATORS 2026",
    home_sponsors_title: "SPONSORS",
    home_videos_title: "AFTER MOVIES",
    tickets_title: "TICKETS",
    tickets_general: "General Admission",
    tickets_competition: "Competition Fee",
    location_title: "LOCATION",
    location_address: "Par. Leoforos Kifissou 42, Egaleo",
    location_map_btn: "View on Map",
    contact_title: "CONTACT",
    photos_title: "PHOTOS",
    sponsors_title: "SPONSORS",
    program_title: "PROGRAM",
    program_mainstage: "Main Stage",
    competition_title: "COMPETITION",
    student_title: "STUDENT COMPETITION",
    rules_title: "RULES & TERMS",
    fees_title: "ENTRY FEES",
    coming_soon: "Coming soon...",
    learn_more: "Learn more →",
    register_now: "REGISTER",
    view_map: "VIEW MAP",
    location_desc1: "The 8th Greek Barber Festival will take place at the historic \"Klostai Petaloda\" textile factory at Par. Leoforos Kifissou 42, Egaleo.",
    location_desc2: "The venue is easily accessible by Metro, just 11-12 minutes walk from Egaleo and Eleonas stations.",
    location_cartel: "( next to \"CARTEL\" Techno Space )",
    location_date: "April 26-27, 2026 — ATHENS",
    contact_person_label: "Contact Person",
    contact_follow: "Find us & Follow us",
    program_stage_desc: "View the main stage schedule",
    program_stage_btn: "STAGE SCHEDULE",
    comp_description: "Description",
    comp_requirements: "Requirements:",
    comp_criteria: "Criteria:",
    comp_time: "Time:",
    fees_desc: "For full pricing and registration:",
    fees_link: "Go to competition fees page",
    mainstage_coming: "Schedule coming soon",
    mainstage_note: "The full main stage schedule will be published before the event.",
    general_admission_title: "GENERAL ADMISSION",
    comp_fee_title: "COMPETITION FEES",
    home_about: "The 8th Greek Barber Festival is the meeting point of barber culture in Greece. For 2 days the iconic industrial spaces of the historic «Klostai Petaloda» textile factory in Athens transform into a center of inspiration, education and creativity. Live presentations, educational seminars and competitions create a unique experience of knowledge, inspiration and professional growth.",
    home_tagline: "Education - Evolution - Success",
    home_date: "April 26-27, 2026",
    comp_topics_title: "COMPETITION CATEGORIES",
    comp_overview_intro: "The biggest competition in Greece featuring top barbers with worldwide recognition. The competition meets European standards and judges are internationally recognized educators from across Europe. Register and compete for the title «Best Barber of the Year 2026» plus great prizes. There are 4 categories. You may enter one or more. At least 3 categories are required for the title.",
    presale_title: "Pre-sale until February 28, 2026",
    crew_presale_title: "Festival Crew Bonus — Pre-sale",
    crew_general_title: "Festival Crew Bonus — General Admission",
    special_prices: "Take advantage of special prices.",
    professionals: "Professionals*",
    students_label: "Students*",
    prof_desc: "*Shop owners, employees, freelancers, graduates of private or public school.",
    student_desc: "*(proof of enrollment required)",
    companions_note: "Note: Companions (1st degree relatives) may attend with general admission €30.00",
    info_phones: "For more information call:",
    form_title: "REGISTRATION FORM",
    form_name: "Name",
    form_surname: "Surname",
    form_phone: "Phone",
    form_postal: "Postal Code",
    form_address: "Address",
    form_city: "City",
    form_category: "Select category",
    form_professional: "Professional",
    form_student_opt: "Student",
    prof_comp_title: "PROFESSIONAL COMPETITION",
    one_topic_label: "For 1 competition category:",
    multi_topics_title: "Multiple categories",
    student_comp_fees: "STUDENT COMPETITION",
    free_admission: "(FREE general admission)",
    comp_fee_notes: "*Model names must be registered 15 days in advance. *Models for 1-2 categories: €50 admission. *Models unrelated to the industry must leave after their category ends.",
    best_barber_note: "For the «Best Barber of the Year» title → at least 3 categories.",
    comp_single_note: "*The above prices apply for a single competition category.",
    per_person: "/ person",
    bonus_note: "10-point bonus from each judge, awarded to one competitor only.",
    tickets_prof_students: "Professionals & Students",
    tickets_cost_note: "Cost per category / multiple categories",
    tickets_more: "MORE INFO",
    photos_thanks: "Thank you all for being with us!",
    photos_download: "You can download the photos, like them, and share them on social media.",
    photos_see_you: "See you at the 8th Greek Barber Festival April 26-27, 2026, ATHENS",
    student_notes_title: "Important Notes",
    student_registration: "REGISTER NOW",
    student_terms: "I accept the rules and confirm participation in both competition categories",
    student_intro: "As part of the 8th Greek Barber Festival, a student competition will be organized.",
    student_eligibility: "Students from public, private, EPAL and IEK hairdressing schools may participate.",
    student_awards: "Awards will recognize the skills and performance of competing students, judged by the strictest criteria. There are 2 competition categories:",
    student_mandatory: "Participation in both competition categories is mandatory.",
    student_price_note: "(festival admission is included in the price)",
    student_fast_time: "Time: 15 minutes",
    student_fast_desc: "This category is about the fastest and best barber.",
    student_freestyle_time: "Time: 60 minutes",
    student_freestyle_desc: "Compete in a freestyle category using your imagination.",
    student_contact_note: "For more information contact us at",
    footer_phones: "Contact Phones",
    footer_links: "Links",
    footer_date_venue: "April 26-27, 2026 ATHENS",
    hero_city: "ATHENS",
    hero_factory: "FACTORY «KLOSTAI PETALODA»",
    hero_address_short: "Par. Leoforos Kifissou 42, Egaleo (next to «Cartel» Techno Space)",
    hero_tickets_btn: "TICKETS",
    hero_competition_btn: "COMPETITION",
    countdown_days: "DAYS",
    countdown_hours: "HOURS",
    countdown_minutes: "MINS",
    countdown_seconds: "SECS",
    comp_notes_title: "Important Notes",
    comp_notes_more: "For more information about the rules,",
    comp_notes_link: "view the Terms & Conditions",
    comp_cat_oldschool_desc: "Compete in an old school haircut of your choice.",
    comp_cat_modern_desc: "Compete in a modern haircut of your choice.",
    comp_cat_fastest_desc: "This category is about the fastest and most precise barber.",
    comp_cat_freestyle_desc: "Compete in a freestyle category using your imagination.",
    comp_cat_time_unit: "min",
    nav_student_comp: "Student Competition",
    nav_comp_cost: "Competition Fees",
    nav_comp_rules: "Terms & Conditions",
  },
  es: {
    nav_tickets: "ENTRADAS",
    nav_program: "PROGRAMA",
    nav_competition: "COMPETICIÓN",
    nav_photos: "FOTOS",
    nav_sponsors: "PATROCINADORES",
    nav_contact: "CONTACTO",
    nav_location: "UBICACIÓN",
    nav_general_admission: "Entrada General",
    nav_competition_cost: "Competición",
    nav_mainstage: "Escenario Principal",
    nav_competition_topics: "Categorías",
    nav_student: "Competición Estudiantil",
    nav_fees: "Cuotas de Inscripción",
    nav_rules: "Reglamento",
    home_hero_subtitle: "EDUCACIÓN · SHOWS · COMPETICIONES",
    home_hero_cta: "COMPRAR ENTRADAS",
    home_educators_title: "EDUCADORES INVITADOS 2026",
    home_sponsors_title: "PATROCINADORES",
    home_videos_title: "AFTER MOVIES",
    tickets_title: "ENTRADAS",
    tickets_general: "Entrada General",
    tickets_competition: "Cuota de Competición",
    location_title: "UBICACIÓN",
    location_address: "Par. Leoforos Kifissou 42, Egaleo",
    location_map_btn: "Ver en el mapa",
    contact_title: "CONTACTO",
    photos_title: "FOTOS",
    sponsors_title: "PATROCINADORES",
    program_title: "PROGRAMA",
    program_mainstage: "Escenario Principal",
    competition_title: "COMPETICIÓN",
    student_title: "COMPETICIÓN ESTUDIANTIL",
    rules_title: "REGLAMENTO",
    fees_title: "CUOTAS DE INSCRIPCIÓN",
    coming_soon: "Próximamente...",
    learn_more: "Más info →",
    register_now: "INSCRIBIRSE",
    view_map: "VER MAPA",
    location_desc1: "El 8º Greek Barber Festival tendrá lugar en la histórica fábrica textil \"Klostai Petaloda\" en Par. Leoforos Kifissou 42, Egaleo.",
    location_desc2: "El recinto es fácilmente accesible en Metro, a solo 11-12 minutos a pie de las estaciones de Egaleo y Eleonas.",
    location_cartel: "( junto al espacio tecno \"CARTEL\" )",
    location_date: "26-27 de abril de 2026 — ATENAS",
    contact_person_label: "Persona de Contacto",
    contact_follow: "Encuéntranos y síguenos",
    program_stage_desc: "Ver el programa del escenario principal",
    program_stage_btn: "PROGRAMA DEL ESCENARIO",
    comp_description: "Descripción",
    comp_requirements: "Requisitos:",
    comp_criteria: "Criterios:",
    comp_time: "Tiempo:",
    fees_desc: "Para precios completos e inscripción:",
    fees_link: "Ir a la página de tarifas",
    mainstage_coming: "Programa próximamente",
    mainstage_note: "El programa completo del escenario principal se publicará antes del evento.",
    general_admission_title: "ENTRADA GENERAL",
    comp_fee_title: "CUOTAS DE COMPETICIÓN",
    home_about: "El 8º Greek Barber Festival es el punto de encuentro de la cultura barber en Grecia. Durante 2 días, los emblemáticos espacios industriales de la histórica fábrica textil «Klostai Petaloda» en Atenas se convierten en un centro de inspiración, educación y creatividad. Presentaciones en vivo, seminarios educativos y competiciones crean una experiencia única de conocimiento, inspiración y desarrollo profesional.",
    home_tagline: "Educación - Evolución - Éxito",
    home_date: "26-27 de abril de 2026",
    comp_topics_title: "CATEGORÍAS DE COMPETICIÓN",
    comp_overview_intro: "La mayor competición de Grecia con los mejores barberos de reconocimiento mundial. La competición cumple estándares europeos y los jueces son educadores internacionales reconocidos de toda Europa. Inscríbete y compite por el título «Best Barber of the Year 2026» y grandes premios. Hay 4 categorías. Puedes inscribirte en una o más. Se requieren al menos 3 categorías para el título.",
    presale_title: "Preventa hasta el 28 de febrero de 2026",
    crew_presale_title: "Festival Crew Bonus — Preventa",
    crew_general_title: "Festival Crew Bonus — Entrada General",
    special_prices: "Aprovecha los precios especiales.",
    professionals: "Profesionales*",
    students_label: "Estudiantes*",
    prof_desc: "*Propietarios y empleados de tiendas, freelancers, graduados de escuelas privadas o públicas.",
    student_desc: "*(se requiere certificado de estudios)",
    companions_note: "Nota: Se permiten acompañantes (1er grado de parentesco) con entrada general €30.00",
    info_phones: "Para más información llame al:",
    form_title: "FORMULARIO DE INSCRIPCIÓN",
    form_name: "Nombre",
    form_surname: "Apellido",
    form_phone: "Teléfono",
    form_postal: "Código Postal",
    form_address: "Dirección",
    form_city: "Ciudad",
    form_category: "Seleccionar categoría",
    form_professional: "Profesional",
    form_student_opt: "Estudiante",
    prof_comp_title: "COMPETICIÓN PROFESIONAL",
    one_topic_label: "Para 1 categoría de competición:",
    multi_topics_title: "Múltiples categorías",
    student_comp_fees: "COMPETICIÓN ESTUDIANTIL",
    free_admission: "(entrada general GRATUITA)",
    comp_fee_notes: "*Los nombres de los modelos deben registrarse 15 días antes. *Modelos para 1-2 categorías: €50 entrada. *Modelos sin relación con el sector deben salir tras su categoría.",
    best_barber_note: "Para el título «Best Barber of the Year» → al menos 3 categorías.",
    comp_single_note: "*Los precios anteriores son válidos para una sola categoría.",
    per_person: "/ persona",
    bonus_note: "10 puntos extra de cada juez, otorgados a un solo competidor.",
    tickets_prof_students: "Profesionales y Estudiantes",
    tickets_cost_note: "Precio por categoría / múltiples categorías",
    tickets_more: "MÁS INFO",
    photos_thanks: "¡Gracias a todos los que estuvieron con nosotros!",
    photos_download: "Puedes descargar las fotos, darles «me gusta» y compartirlas en redes sociales.",
    photos_see_you: "¡Nos vemos en el 8º Greek Barber Festival 26-27 de abril de 2026, ATENAS!",
    student_notes_title: "Notas Importantes",
    student_registration: "INSCRIBIRSE",
    student_terms: "Acepto el reglamento y confirmo mi participación en ambas categorías",
    student_intro: "En el marco del 8º Greek Barber Festival se organizará una competición estudiantil.",
    student_eligibility: "Pueden participar estudiantes de escuelas de peluquería públicas, privadas y de formación profesional.",
    student_awards: "Los premios reconocerán las habilidades de los competidores, evaluados con los criterios más estrictos. Hay 2 categorías:",
    student_mandatory: "La participación en ambas categorías es obligatoria.",
    student_price_note: "(la entrada al festival está incluida en el precio)",
    student_fast_time: "Tiempo: 15 minutos",
    student_fast_desc: "Esta categoría es para el barbero más rápido y preciso.",
    student_freestyle_time: "Tiempo: 60 minutos",
    student_freestyle_desc: "Compite en una categoría libre usando tu imaginación.",
    student_contact_note: "Para más información contáctanos en",
    footer_phones: "Teléfonos de Contacto",
    footer_links: "Enlace",
    footer_date_venue: "26-27 de abril de 2026 ATENAS",
    hero_city: "ATENAS",
    hero_factory: "FÁBRICA «KLOSTAI PETALODA»",
    hero_address_short: "Par. Leoforos Kifissou 42, Egaleo (junto a «Cartel»)",
    hero_tickets_btn: "ENTRADAS",
    hero_competition_btn: "COMPETICIÓN",
    countdown_days: "DÍAS",
    countdown_hours: "HORAS",
    countdown_minutes: "MINS",
    countdown_seconds: "SEGS",
    comp_notes_title: "Notas Importantes",
    comp_notes_more: "Para más información sobre las normas,",
    comp_notes_link: "ver los Términos y Condiciones",
    comp_cat_oldschool_desc: "Compite en un corte old school de tu elección.",
    comp_cat_modern_desc: "Compite en un corte modern barbering de tu elección.",
    comp_cat_fastest_desc: "Esta categoría es para el barbero más rápido y preciso.",
    comp_cat_freestyle_desc: "Compite en una categoría libre usando tu imaginación.",
    comp_cat_time_unit: "min",
    nav_student_comp: "Competición Estudiantil",
    nav_comp_cost: "Cuotas de Inscripción",
    nav_comp_rules: "Reglamento",
  },
  ar: {
    nav_tickets: "التذاكر",
    nav_program: "البرنامج",
    nav_competition: "المسابقة",
    nav_photos: "الصور",
    nav_sponsors: "الرعاة",
    nav_contact: "التواصل",
    nav_location: "الموقع",
    nav_general_admission: "الدخول العام",
    nav_competition_cost: "المسابقة",
    nav_mainstage: "المسرح الرئيسي",
    nav_competition_topics: "فئات المسابقة",
    nav_student: "مسابقة الطلاب",
    nav_fees: "رسوم الاشتراك",
    nav_rules: "الشروط والأحكام",
    home_hero_subtitle: "تعليم · عروض · منافسات",
    home_hero_cta: "شراء التذاكر",
    home_educators_title: "المعلمون الضيوف 2026",
    home_sponsors_title: "الرعاة",
    home_videos_title: "أفلام ما بعد المهرجان",
    tickets_title: "التذاكر",
    tickets_general: "الدخول العام",
    tickets_competition: "رسوم المسابقة",
    location_title: "الموقع",
    location_address: "ليوفوروس كيفيسو 42، إيغاليو",
    location_map_btn: "عرض على الخريطة",
    contact_title: "التواصل",
    photos_title: "الصور",
    sponsors_title: "الرعاة",
    program_title: "البرنامج",
    program_mainstage: "المسرح الرئيسي",
    competition_title: "المسابقة",
    student_title: "مسابقة الطلاب",
    rules_title: "الشروط والأحكام",
    fees_title: "رسوم الاشتراك",
    coming_soon: "قريباً...",
    learn_more: "المزيد ←",
    register_now: "تسجيل",
    view_map: "عرض الخريطة",
    location_desc1: "سيُقام مهرجان الحلاقة اليوناني الثامن في مصنع \"كلوستاي بيتالودا\" التاريخي في شارع ليوفوروس كيفيسو 42، إيغاليو.",
    location_desc2: "يمكن الوصول إلى المكان بسهولة عبر مترو الأنفاق، على بُعد 11-12 دقيقة سيرًا من محطتي إيغاليو وإيلاوناس.",
    location_cartel: "( بجانب مساحة \"CARTEL\" التقنية )",
    location_date: "26-27 أبريل 2026 — أثينا",
    contact_person_label: "شخص الاتصال",
    contact_follow: "ابحث عنا وتابعنا",
    program_stage_desc: "عرض جدول المسرح الرئيسي",
    program_stage_btn: "جدول المسرح",
    comp_description: "الوصف",
    comp_requirements: "المتطلبات:",
    comp_criteria: "المعايير:",
    comp_time: "الوقت:",
    fees_desc: "للاطلاع على الأسعار الكاملة والتسجيل:",
    fees_link: "انتقل إلى صفحة رسوم المسابقة",
    mainstage_coming: "الجدول قريباً",
    mainstage_note: "سيتم نشر الجدول الكامل للمسرح الرئيسي قبل الحدث.",
    general_admission_title: "الدخول العام",
    comp_fee_title: "رسوم المسابقة",
    home_about: "مهرجان الحلاقة اليوناني الثامن هو نقطة التقاء ثقافة الحلاقة في اليونان. لمدة يومين تتحول المباني الصناعية الأيقونية لمصنع «كلوستاي بيتالودا» التاريخي في أثينا إلى مركز للإلهام والتعليم والإبداع. العروض الحية والندوات التعليمية والمنافسات تخلق تجربة فريدة من المعرفة والإلهام والنمو المهني.",
    home_tagline: "تعليم - تطور - نجاح",
    home_date: "26-27 أبريل 2026",
    comp_topics_title: "فئات المسابقة",
    comp_overview_intro: "أكبر مسابقة في اليونان تضم أفضل الحلاقين المعترف بهم عالمياً. تستوفي المسابقة المعايير الأوروبية والحكام مدربون دوليون معترف بهم من جميع أنحاء أوروبا. سجل وتنافس على لقب «أفضل حلاق لعام 2026» وجوائز قيّمة. هناك 4 فئات يمكنك الاشتراك في واحدة أو أكثر. مطلوب 3 فئات على الأقل للحصول على اللقب.",
    presale_title: "البيع المسبق حتى 28 فبراير 2026",
    crew_presale_title: "Festival Crew Bonus — البيع المسبق",
    crew_general_title: "Festival Crew Bonus — الدخول العام",
    special_prices: "استفد من الأسعار الخاصة.",
    professionals: "المحترفون*",
    students_label: "الطلاب*",
    prof_desc: "*أصحاب المحلات والموظفون والعمال المستقلون وخريجو المدارس.",
    student_desc: "*(شهادة التسجيل مطلوبة)",
    companions_note: "ملاحظة: يُسمح للمرافقين (الدرجة الأولى من الأقارب) بالدخول العام بسعر €30.00",
    info_phones: "للمزيد من المعلومات اتصل بـ:",
    form_title: "نموذج التسجيل",
    form_name: "الاسم",
    form_surname: "اللقب",
    form_phone: "الهاتف",
    form_postal: "الرمز البريدي",
    form_address: "العنوان",
    form_city: "المدينة",
    form_category: "اختر الفئة",
    form_professional: "محترف",
    form_student_opt: "طالب",
    prof_comp_title: "المسابقة الاحترافية",
    one_topic_label: "لفئة مسابقة واحدة:",
    multi_topics_title: "فئات متعددة",
    student_comp_fees: "مسابقة الطلاب",
    free_admission: "(دخول عام مجاني)",
    comp_fee_notes: "*يجب تسجيل أسماء الموديلات قبل 15 يوماً. *الموديلات لـ 1-2 فئة: €50 دخول. *الموديلات غير المرتبطة بالقطاع يجب مغادرة القاعة بعد انتهاء فئتهم.",
    best_barber_note: "للحصول على لقب «أفضل حلاق» ← على الأقل 3 فئات.",
    comp_single_note: "*الأسعار أعلاه سارية لفئة مسابقة واحدة فقط.",
    per_person: "/ شخص",
    bonus_note: "10 نقاط إضافية من كل حكم، تُمنح لمتسابق واحد فقط.",
    tickets_prof_students: "محترفون وطلاب",
    tickets_cost_note: "تكلفة لكل فئة / فئات متعددة",
    tickets_more: "المزيد",
    photos_thanks: "شكراً لكم جميعاً على مشاركتكم معنا!",
    photos_download: "يمكنكم تحميل الصور والإعجاب بها ومشاركتها على وسائل التواصل الاجتماعي.",
    photos_see_you: "نلتقي في مهرجان الحلاقة اليوناني الثامن 26-27 أبريل 2026، أثينا",
    student_notes_title: "ملاحظات مهمة",
    student_registration: "التسجيل",
    student_terms: "أوافق على القواعد وأؤكد مشاركتي في كلتا الفئتين",
    student_intro: "في إطار مهرجان الحلاقة اليوناني الثامن سيُنظَّم مسابقة طلابية.",
    student_eligibility: "يمكن للطلاب من مدارس الحلاقة العامة والخاصة والمهنية المشاركة.",
    student_awards: "ستُكرَّم المهارات والأداء المتميز للمتسابقين بأشد المعايير صرامة. الفئتان المتنافَس فيهما:",
    student_mandatory: "المشاركة في كلتا الفئتين إلزامية.",
    student_price_note: "(تشمل التذكرة الدخول إلى المهرجان)",
    student_fast_time: "الوقت: 15 دقيقة",
    student_fast_desc: "هذه الفئة تختص بأسرع وأفضل حلاق.",
    student_freestyle_time: "الوقت: 60 دقيقة",
    student_freestyle_desc: "تنافس في فئة حرة باستخدام خيالك.",
    student_contact_note: "للمزيد من المعلومات تواصل معنا على",
    footer_phones: "هواتف التواصل",
    footer_links: "روابط",
    footer_date_venue: "26-27 أبريل 2026 أثينا",
    hero_city: "أثينا",
    hero_factory: "مصنع «كلوستاي بيتالودا»",
    hero_address_short: "شارع ليوفوروس كيفيسو 42، إيغاليو (بجانب «كارتيل»)",
    hero_tickets_btn: "التذاكر",
    hero_competition_btn: "المسابقة",
    countdown_days: "أيام",
    countdown_hours: "ساعات",
    countdown_minutes: "دقائق",
    countdown_seconds: "ثواني",
    comp_notes_title: "ملاحظات مهمة",
    comp_notes_more: "للمزيد من المعلومات حول القواعد،",
    comp_notes_link: "عرض الشروط والأحكام",
    comp_cat_oldschool_desc: "تنافس في قصة شعر كلاسيكية من اختيارك.",
    comp_cat_modern_desc: "تنافس في قصة شعر modern barbering من اختيارك.",
    comp_cat_fastest_desc: "هذه الفئة تختص بأسرع وأدق حلاق.",
    comp_cat_freestyle_desc: "تنافس في فئة حرة باستخدام خيالك.",
    comp_cat_time_unit: "دقيقة",
    nav_student_comp: "مسابقة الطلاب",
    nav_comp_cost: "رسوم الاشتراك",
    nav_comp_rules: "الشروط والأحكام",
  },
  pt: {
    nav_tickets: "BILHETES",
    nav_program: "PROGRAMA",
    nav_competition: "COMPETIÇÃO",
    nav_photos: "FOTOS",
    nav_sponsors: "PATROCINADORES",
    nav_contact: "CONTACTO",
    nav_location: "LOCALIZAÇÃO",
    nav_general_admission: "Entrada Geral",
    nav_competition_cost: "Competição",
    nav_mainstage: "Palco Principal",
    nav_competition_topics: "Categorias",
    nav_student: "Competição Estudantil",
    nav_fees: "Taxas de Inscrição",
    nav_rules: "Regulamento",
    home_hero_subtitle: "EDUCAÇÃO · SHOWS · COMPETIÇÕES",
    home_hero_cta: "COMPRAR BILHETES",
    home_educators_title: "EDUCADORES CONVIDADOS 2026",
    home_sponsors_title: "PATROCINADORES",
    home_videos_title: "AFTER MOVIES",
    tickets_title: "BILHETES",
    tickets_general: "Entrada Geral",
    tickets_competition: "Taxa de Competição",
    location_title: "LOCALIZAÇÃO",
    location_address: "Par. Leoforos Kifissou 42, Egaleo",
    location_map_btn: "Ver no mapa",
    contact_title: "CONTACTO",
    photos_title: "FOTOS",
    sponsors_title: "PATROCINADORES",
    program_title: "PROGRAMA",
    program_mainstage: "Palco Principal",
    competition_title: "COMPETIÇÃO",
    student_title: "COMPETIÇÃO ESTUDANTIL",
    rules_title: "REGULAMENTO",
    fees_title: "TAXAS DE INSCRIÇÃO",
    coming_soon: "Em breve...",
    learn_more: "Saiba mais →",
    register_now: "INSCREVER",
    view_map: "VER MAPA",
    location_desc1: "O 8º Greek Barber Festival terá lugar na histórica fábrica têxtil \"Klostai Petaloda\" na Par. Leoforos Kifissou 42, Egaleo.",
    location_desc2: "O local é facilmente acessível de Metro, a apenas 11-12 minutos a pé das estações de Egaleo e Eleonas.",
    location_cartel: "( ao lado do espaço tecno \"CARTEL\" )",
    location_date: "26-27 de abril de 2026 — ATENAS",
    contact_person_label: "Pessoa de Contacto",
    contact_follow: "Encontre-nos e siga-nos",
    program_stage_desc: "Ver o programa do palco principal",
    program_stage_btn: "PROGRAMA DO PALCO",
    comp_description: "Descrição",
    comp_requirements: "Requisitos:",
    comp_criteria: "Critérios:",
    comp_time: "Tempo:",
    fees_desc: "Para preços completos e inscrição:",
    fees_link: "Ir à página de taxas de inscrição",
    mainstage_coming: "Programa em breve",
    mainstage_note: "O programa completo do palco principal será publicado antes do evento.",
    general_admission_title: "ENTRADA GERAL",
    comp_fee_title: "TAXAS DE COMPETIÇÃO",
    home_about: "O 8º Greek Barber Festival é o ponto de encontro da cultura barber na Grécia. Durante 2 dias, os emblemáticos espaços industriais da histórica fábrica têxtil «Klostai Petaloda» em Atenas transformam-se num centro de inspiração, educação e criatividade. Apresentações ao vivo, seminários educacionais e competições criam uma experiência única de conhecimento, inspiração e crescimento profissional.",
    home_tagline: "Educação - Evolução - Sucesso",
    home_date: "26-27 de abril de 2026",
    comp_topics_title: "CATEGORIAS DE COMPETIÇÃO",
    comp_overview_intro: "A maior competição da Grécia com os melhores barbeiros de reconhecimento mundial. A competição cumpre padrões europeus e os juízes são educadores internacionais reconhecidos de toda a Europa. Inscreva-se e dispute o título «Best Barber of the Year 2026» e grandes prémios. Há 4 categorias. Pode inscrever-se em uma ou mais. São necessárias pelo menos 3 categorias para o título.",
    presale_title: "Pré-venda até 28 de fevereiro de 2026",
    crew_presale_title: "Festival Crew Bonus — Pré-venda",
    crew_general_title: "Festival Crew Bonus — Entrada Geral",
    special_prices: "Aproveite os preços especiais.",
    professionals: "Profissionais*",
    students_label: "Estudantes*",
    prof_desc: "*Proprietários e funcionários de lojas, freelancers, licenciados de escolas privadas ou públicas.",
    student_desc: "*(comprovativo de matrícula obrigatório)",
    companions_note: "Nota: São permitidos acompanhantes (1º grau de parentesco) com entrada geral €30.00",
    info_phones: "Para mais informações ligue para:",
    form_title: "FORMULÁRIO DE INSCRIÇÃO",
    form_name: "Nome",
    form_surname: "Apelido",
    form_phone: "Telefone",
    form_postal: "Código Postal",
    form_address: "Morada",
    form_city: "Cidade",
    form_category: "Selecionar categoria",
    form_professional: "Profissional",
    form_student_opt: "Estudante",
    prof_comp_title: "COMPETIÇÃO PROFISSIONAL",
    one_topic_label: "Para 1 categoria de competição:",
    multi_topics_title: "Múltiplas categorias",
    student_comp_fees: "COMPETIÇÃO ESTUDANTIL",
    free_admission: "(entrada geral GRATUITA)",
    comp_fee_notes: "*Os nomes dos modelos devem ser registados 15 dias antes. *Modelos para 1-2 categorias: €50 entrada. *Modelos sem ligação ao setor devem sair após a sua categoria.",
    best_barber_note: "Para o título «Best Barber of the Year» → pelo menos 3 categorias.",
    comp_single_note: "*Os preços acima aplicam-se para uma única categoria.",
    per_person: "/ pessoa",
    bonus_note: "Bónus de 10 pontos de cada juiz, atribuído a um único competidor.",
    tickets_prof_students: "Profissionais e Estudantes",
    tickets_cost_note: "Custo por categoria / múltiplas categorias",
    tickets_more: "MAIS INFO",
    photos_thanks: "Obrigado a todos que estiveram connosco!",
    photos_download: "Pode descarregar as fotos, dar «gosto» e partilhá-las nas redes sociais.",
    photos_see_you: "Até ao 8º Greek Barber Festival 26-27 de abril de 2026, ATENAS",
    student_notes_title: "Notas Importantes",
    student_registration: "INSCREVER",
    student_terms: "Aceito o regulamento e confirmo participação em ambas as categorias",
    student_intro: "No âmbito do 8º Greek Barber Festival será organizada uma competição estudantil.",
    student_eligibility: "Podem participar alunos de escolas de cabeleireiro públicas, privadas e profissionais.",
    student_awards: "Os prémios reconhecerão as competências dos concorrentes, avaliados pelos critérios mais rigorosos. Há 2 categorias:",
    student_mandatory: "A participação em ambas as categorias é obrigatória.",
    student_price_note: "(a entrada no festival está incluída no preço)",
    student_fast_time: "Tempo: 15 minutos",
    student_fast_desc: "Esta categoria é para o barbeiro mais rápido e preciso.",
    student_freestyle_time: "Tempo: 60 minutos",
    student_freestyle_desc: "Compita numa categoria livre usando a sua imaginação.",
    student_contact_note: "Para mais informações contacte-nos em",
    footer_phones: "Telefones de Contacto",
    footer_links: "Ligações",
    footer_date_venue: "26-27 de abril de 2026 ATENAS",
    hero_city: "ATENAS",
    hero_factory: "FÁBRICA «KLOSTAI PETALODA»",
    hero_address_short: "Par. Leoforos Kifissou 42, Egaleo (junto a «Cartel»)",
    hero_tickets_btn: "BILHETES",
    hero_competition_btn: "COMPETIÇÃO",
    countdown_days: "DIAS",
    countdown_hours: "HORAS",
    countdown_minutes: "MINS",
    countdown_seconds: "SEGS",
    comp_notes_title: "Notas Importantes",
    comp_notes_more: "Para mais informações sobre as regras,",
    comp_notes_link: "ver os Termos e Condições",
    comp_cat_oldschool_desc: "Compita num corte old school à sua escolha.",
    comp_cat_modern_desc: "Compita num corte modern barbering à sua escolha.",
    comp_cat_fastest_desc: "Esta categoria é para o barbeiro mais rápido e preciso.",
    comp_cat_freestyle_desc: "Compita numa categoria livre usando a sua imaginação.",
    comp_cat_time_unit: "min",
    nav_student_comp: "Competição Estudantil",
    nav_comp_cost: "Taxas de Inscrição",
    nav_comp_rules: "Regulamento",
  },
  de: {
    nav_tickets: "TICKETS",
    nav_program: "PROGRAMM",
    nav_competition: "WETTBEWERB",
    nav_photos: "FOTOS",
    nav_sponsors: "SPONSOREN",
    nav_contact: "KONTAKT",
    nav_location: "STANDORT",
    nav_general_admission: "Allgemeiner Eintritt",
    nav_competition_cost: "Wettbewerb",
    nav_mainstage: "Hauptbühne",
    nav_competition_topics: "Kategorien",
    nav_student: "Schülerwettbewerb",
    nav_fees: "Teilnahmegebühren",
    nav_rules: "Regeln & Bedingungen",
    home_hero_subtitle: "BILDUNG · SHOWS · WETTBEWERBE",
    home_hero_cta: "TICKETS KAUFEN",
    home_educators_title: "GAST-EDUCATORS 2026",
    home_sponsors_title: "SPONSOREN",
    home_videos_title: "AFTER MOVIES",
    tickets_title: "TICKETS",
    tickets_general: "Allgemeiner Eintritt",
    tickets_competition: "Wettbewerbsgebühr",
    location_title: "STANDORT",
    location_address: "Par. Leoforos Kifissou 42, Egaleo",
    location_map_btn: "Karte anzeigen",
    contact_title: "KONTAKT",
    photos_title: "FOTOS",
    sponsors_title: "SPONSOREN",
    program_title: "PROGRAMM",
    program_mainstage: "Hauptbühne",
    competition_title: "WETTBEWERB",
    student_title: "SCHÜLERWETTBEWERB",
    rules_title: "REGELN & BEDINGUNGEN",
    fees_title: "TEILNAHMEGEBÜHREN",
    coming_soon: "Demnächst...",
    learn_more: "Mehr erfahren →",
    register_now: "ANMELDEN",
    view_map: "KARTE ANZEIGEN",
    location_desc1: "Das 8. Greek Barber Festival findet in der historischen Textilfabrik \"Klostai Petaloda\" in der Par. Leoforos Kifissou 42, Egaleo statt.",
    location_desc2: "Das Veranstaltungsgelände ist einfach per U-Bahn erreichbar, nur 11-12 Minuten Fußweg von den Stationen Egaleo und Eleonas.",
    location_cartel: "( neben dem Techno-Raum \"CARTEL\" )",
    location_date: "26.-27. April 2026 — ATHEN",
    contact_person_label: "Ansprechperson",
    contact_follow: "Finden Sie uns & folgen Sie uns",
    program_stage_desc: "Programm der Hauptbühne ansehen",
    program_stage_btn: "BÜHNEN-PROGRAMM",
    comp_description: "Beschreibung",
    comp_requirements: "Voraussetzungen:",
    comp_criteria: "Kriterien:",
    comp_time: "Zeit:",
    fees_desc: "Für vollständige Preise und Anmeldung:",
    fees_link: "Zur Gebührenseite",
    mainstage_coming: "Programm demnächst",
    mainstage_note: "Das vollständige Hauptbühnen-Programm wird vor der Veranstaltung veröffentlicht.",
    general_admission_title: "ALLGEMEINER EINTRITT",
    comp_fee_title: "WETTBEWERBSGEBÜHREN",
    home_about: "Das 8. Greek Barber Festival ist der Treffpunkt der Barber-Kultur in Griechenland. Für 2 Tage verwandeln sich die ikonischen Industrieräume der historischen Textilfabrik «Klostai Petaloda» in Athen in ein Zentrum für Inspiration, Bildung und Kreativität. Live-Präsentationen, Bildungsseminare und Wettbewerbe schaffen ein einzigartiges Erlebnis aus Wissen, Inspiration und beruflicher Weiterentwicklung.",
    home_tagline: "Bildung - Entwicklung - Erfolg",
    home_date: "26.-27. April 2026",
    comp_topics_title: "WETTBEWERBSKATEGORIEN",
    comp_overview_intro: "Der größte Wettbewerb Griechenlands mit Top-Barbieren von weltweiter Bekanntheit. Der Wettbewerb erfüllt europäische Standards und die Jury besteht aus international anerkannten Trainern aus ganz Europa. Melden Sie sich an und kämpfen Sie um den Titel «Best Barber of the Year 2026» sowie tolle Preise. Es gibt 4 Kategorien. Sie können sich für eine oder mehrere anmelden. Mindestens 3 Kategorien sind für den Titel erforderlich.",
    presale_title: "Vorverkauf bis 28. Februar 2026",
    crew_presale_title: "Festival Crew Bonus — Vorverkauf",
    crew_general_title: "Festival Crew Bonus — Allgemeiner Eintritt",
    special_prices: "Profitieren Sie von Sonderpreisen.",
    professionals: "Fachleute*",
    students_label: "Schüler*",
    prof_desc: "*Ladenbesitzer, Angestellte, Freelancer, Absolventen privater oder öffentlicher Schulen.",
    student_desc: "*(Immatrikulationsnachweis erforderlich)",
    companions_note: "Hinweis: Begleitpersonen (1. Verwandtschaftsgrad) dürfen mit allgemeinem Eintritt €30.00 teilnehmen",
    info_phones: "Für weitere Informationen rufen Sie an:",
    form_title: "ANMELDEFORMULAR",
    form_name: "Vorname",
    form_surname: "Nachname",
    form_phone: "Telefon",
    form_postal: "Postleitzahl",
    form_address: "Adresse",
    form_city: "Stadt",
    form_category: "Kategorie wählen",
    form_professional: "Fachmann",
    form_student_opt: "Schüler",
    prof_comp_title: "PROFIWETTBEWERB",
    one_topic_label: "Für 1 Wettbewerbskategorie:",
    multi_topics_title: "Mehrere Kategorien",
    student_comp_fees: "SCHÜLERWETTBEWERB",
    free_admission: "(KOSTENLOSER allgemeiner Eintritt)",
    comp_fee_notes: "*Modellnamen müssen 15 Tage vorher angemeldet werden. *Modelle für 1-2 Kategorien: €50 Eintritt. *Modelle ohne Branchenbezug müssen nach ihrer Kategorie den Saal verlassen.",
    best_barber_note: "Für den Titel «Best Barber of the Year» → mindestens 3 Kategorien.",
    comp_single_note: "*Obige Preise gelten für eine einzelne Wettbewerbskategorie.",
    per_person: "/ Person",
    bonus_note: "10 Bonuspunkte von jedem Richter, vergeben an nur einen Teilnehmer.",
    tickets_prof_students: "Fachleute & Schüler",
    tickets_cost_note: "Preis pro Kategorie / mehrere Kategorien",
    tickets_more: "MEHR INFO",
    photos_thanks: "Vielen Dank an alle, die mit uns waren!",
    photos_download: "Sie können die Fotos herunterladen, liken und in sozialen Medien teilen.",
    photos_see_you: "Bis zum 8. Greek Barber Festival 26.-27. April 2026, ATHEN",
    student_notes_title: "Wichtige Hinweise",
    student_registration: "ANMELDEN",
    student_terms: "Ich akzeptiere die Regeln und bestätige die Teilnahme an beiden Kategorien",
    student_intro: "Im Rahmen des 8. Greek Barber Festivals wird ein Schülerwettbewerb veranstaltet.",
    student_eligibility: "Schüler öffentlicher, privater und beruflicher Frisierschulen können teilnehmen.",
    student_awards: "Die Preise zeichnen die Fähigkeiten der Teilnehmer aus, bewertet nach strengsten Kriterien. Es gibt 2 Kategorien:",
    student_mandatory: "Die Teilnahme an beiden Kategorien ist Pflicht.",
    student_price_note: "(der Festivaleintritt ist im Preis enthalten)",
    student_fast_time: "Zeit: 15 Minuten",
    student_fast_desc: "Diese Kategorie kürt den schnellsten und besten Barbier.",
    student_freestyle_time: "Zeit: 60 Minuten",
    student_freestyle_desc: "Treten Sie in einer freien Kategorie mit Ihrer Kreativität an.",
    student_contact_note: "Für weitere Informationen kontaktieren Sie uns unter",
    footer_phones: "Kontakttelefone",
    footer_links: "Links",
    footer_date_venue: "26.-27. April 2026 ATHEN",
    hero_city: "ATHEN",
    hero_factory: "FABRIK «KLOSTAI PETALODA»",
    hero_address_short: "Par. Leoforos Kifissou 42, Egaleo (neben «Cartel»)",
    hero_tickets_btn: "TICKETS",
    hero_competition_btn: "WETTBEWERB",
    countdown_days: "TAGE",
    countdown_hours: "STUNDEN",
    countdown_minutes: "MIN",
    countdown_seconds: "SEK",
    comp_notes_title: "Wichtige Hinweise",
    comp_notes_more: "Für weitere Informationen zu den Regeln,",
    comp_notes_link: "Regeln & Bedingungen ansehen",
    comp_cat_oldschool_desc: "Treten Sie in einem Old-School-Haarschnitt Ihrer Wahl an.",
    comp_cat_modern_desc: "Treten Sie in einem Modern-Barbering-Haarschnitt Ihrer Wahl an.",
    comp_cat_fastest_desc: "Diese Kategorie kürt den schnellsten und präzisesten Barbier.",
    comp_cat_freestyle_desc: "Treten Sie in einer freien Kategorie mit Ihrer Kreativität an.",
    comp_cat_time_unit: "Min",
    nav_student_comp: "Schülerwettbewerb",
    nav_comp_cost: "Teilnahmegebühren",
    nav_comp_rules: "Regeln & Bedingungen",
  },
};

interface AppContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: TranslationKey) => string;
  theme: Theme;
  toggleTheme: () => void;
}

const AppContext = createContext<AppContextType>({
  lang: "el",
  setLang: () => {},
  t: (k) => k,
  theme: "dark",
  toggleTheme: () => {},
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>("el");
  const [theme, setTheme] = useState<Theme>("dark");

  useEffect(() => {
    try {
      const savedLang = localStorage.getItem("lang") as Language;
      if (savedLang && T[savedLang]) setLangState(savedLang);
      const savedTheme = localStorage.getItem("theme") as Theme;
      if (savedTheme === "light" || savedTheme === "dark") setTheme(savedTheme);
    } catch {}
  }, []);

  useEffect(() => {
    const dir = LANG_LABELS[lang]?.dir || "ltr";
    document.documentElement.setAttribute("dir", dir);
    document.documentElement.setAttribute("lang", lang);
    try { localStorage.setItem("lang", lang); } catch {}
  }, [lang]);

  const setLang = (l: Language) => setLangState(l);

  const toggleTheme = () => setTheme(prev => {
    const next = prev === "dark" ? "light" : "dark";
    try { localStorage.setItem("theme", next); } catch {}
    return next;
  });

  const t = (key: TranslationKey): string => T[lang]?.[key] ?? T.el[key] ?? key;

  return (
    <AppContext.Provider value={{ lang, setLang, t, theme, toggleTheme }}>
      {children}
    </AppContext.Provider>
  );
}

export function useLanguage() { return useContext(AppContext); }
export function useTheme() { return useContext(AppContext); }
